apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbok
  namespace: cbok
  labels:
    app: cbok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbok
  template:
    metadata:
      labels:
        app: cbok
    spec:
      containers:
        - name: cbok
          image: docker.io/kodanevhy/cbok:latest  # Not a real link, please build by yourself, NOTE referring in Dockerfile
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          command:
            - /tmp/start.sh
          env:
            - name: DB_HOST
              value: "mariadb.cbok.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: cbok
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cbok-db-secret
                  key: password
          volumeMounts:
            - name: startup-script
              mountPath: /tmp/start.sh
              subPath: start.sh
            - name: django-mysql-patch
              mountPath: /tmp/a41b09266dcdd01036d59d76fe926fe0386aaade.patch
      volumes:
        - name: startup-script
          configMap:
            name: cbok
            defaultMode: 0755
        - name: django-mysql-patch
          hostPath:
              path: /opt/foundation/cbok/a41b09266dcdd01036d59d76fe926fe0386aaade.patch
              type: File
